/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height?: number
  width?: number
  aspectRatio?: number
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type Post = {
  _id: string
  _type: 'post'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  slug: Slug
  video: ImagekitVideo
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'blockquote'
        listItem?: 'bullet'
        markDefs?: Array<{
          href?: string
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        asset?: {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
        }
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        _type: 'image'
        _key: string
      }
  >
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top?: number
  bottom?: number
  left?: number
  right?: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x?: number
  y?: number
  height?: number
  width?: number
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type Slug = {
  _type: 'slug'
  current: string
  source?: string
}

export type ImagekitVideo = {
  _type: 'imagekit.video'
  asset?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'imagekit.videoAsset'
  }
}

export type ImagekitVideoAsset = {
  _id: string
  _type: 'imagekit.videoAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  fileId?: string
  status?: string
  url?: string
  filename?: string
  thumbTime?: number
  data?: ImagekitAssetData
}

export type ImagekitAssetData = {
  _type: 'imagekit.assetData'
  resolution?: string
  upload_id?: string
  created_at?: string
  max_resolution?: string
  transformation?: string
  aspect_ratio?: string
  duration?: number
  frame_rate?: number
  quality?: string
  AITags?: Array<string>
  audioCodec?: string
  bitRate?: number
  description?: string
  fileId?: string
  filePath?: string
  fileType?: string
  height?: number
  name?: string
  size?: number
  url?: string
  versionInfo?: {
    id?: string
    name?: string
  }
  videoCodec?: string
  width?: number
  transformations?: Array<
    {
      _key: string
    } & ImagekitTransformation
  >
  video_formats?: ImagekitVideoFormats
}

export type ImagekitVideoFormats = {
  _type: 'imagekit.videoFormats'
  formats?: Array<
    {
      _key: string
    } & ImagekitVideoFormat
  >
}

export type ImagekitVideoFormat = {
  _type: 'imagekit.videoFormat'
  format?: string
  url?: string
  width?: number
  bitrate?: number
  filesize?: number
  height?: number
}

export type ImagekitTransformation = {
  _type: 'imagekit.transformation'
  name?: string
  params?: string
}

export type AllSanitySchemaTypes =
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityFileAsset
  | Geopoint
  | Post
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImageAsset
  | SanityAssetSourceData
  | SanityImageMetadata
  | Slug
  | ImagekitVideo
  | ImagekitVideoAsset
  | ImagekitAssetData
  | ImagekitVideoFormats
  | ImagekitVideoFormat
  | ImagekitTransformation
export declare const internalGroqTypeReferenceTo: unique symbol
// Source: ./src/app/page.tsx
// Variable: postsQuery
// Query: *[_type == "post" && defined(slug.current)]{_id,title,slug,}
export type PostsQueryResult = Array<{
  _id: string
  title: string
  slug: Slug
}>

// Source: ./src/app/posts/[[...slug]]/page.tsx
// Variable: postQuery
// Query: *[_type == "post" && slug.current == $slug][0]{...,"va": video.asset,"video": video.asset->{  url,  fileId}}
export type PostQueryResult = {
  _id: string
  _type: 'post'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  slug: Slug
  video: {
    url: string | null
    fileId: string | null
  } | null
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'normal'
        listItem?: 'bullet'
        markDefs?: Array<{
          href?: string
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        asset?: {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
        }
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        _type: 'image'
        _key: string
      }
  >
  va: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'imagekit.videoAsset'
  } | null
} | null

// Query TypeMap
import '@sanity/client'
declare module '@sanity/client' {
  interface SanityQueries {
    '*[_type == "post" && defined(slug.current)]{\n_id,\ntitle,\nslug,\n}': PostsQueryResult
    '*[_type == "post" && slug.current == $slug][0]{\n...,\n"va": video.asset,\n"video": video.asset->{\n  url,\n  fileId\n}\n}': PostQueryResult
  }
}
